#ifndef _AUTOGEN_METADATA_H_
#define _AUTOGEN_METADATA_H_

#include "StdGType.h"
#include "sxi_defs.h"
#include "<HeaderFileWhereFunctionUnderTestIsDefined>"

/************************************************/
/* Autogenerated Global macros related to tests */
/************************************************/
#define DISABLED                    0
#define ENABLED                     1
#define __TEST_MODE__               ENABLED

/* Return type */
#define RETURN_TYPE                 void
#define __RET_TYP_NOT_VOID__        FALSE

/* Parameter type */
/* e.g. #define PARAM1_TYPE                 SXI_STATUS_IND_STRUCT */
# define PARAM_0_TYPE				BYTE*
# define PARAM_1_TYPE				BYTE*


/* Global types */
# define GLOBAL_0_TYPE				BYTE*
# define GLOBAL_1_TYPE				WORD


/* Number of test cases */
#define MAX_NUM_TEST_CASES          (10)

/* Function under test metadata */
#define PTR_TO_FUNC_UNDER_TEST      void (*fptr)(BYTE*, BYTE*)
#define FUNC_UNDER_TEST             fc_xmc_SaveRcvCatLabel

/*****************************************************/
/* Autogenerated data structure used for test matrix */ 
/*****************************************************/
typedef struct
{
    /* Pointer to function under test */
    PTR_TO_FUNC_UNDER_TEST;

    /* Input arguments to function under test */
    /* e.g.: PARAM1_TYPE	arg1;             */
    PARAM_0_TYPE	arg0;
	PARAM_1_TYPE	arg1;
	

    /* Global types referred by function */
    /* e.g. GLOBAL1_TYPE	global_typ1;*/
    GLOBAL_0_TYPE	global_typ0;
	GLOBAL_1_TYPE	global_typ1;
	

    /* non-void return type */
#if __RET_TYP_NOT_VOID__
    RETURN_TYPE                    ret_val;
#endif

}ST_TEST_INPUTS;


#endif
