#ifndef _AUTOGEN_TESTDATA_H_
#define _AUTOGEN_TESTDATA_H_

#include "AutogeneratedMetadata.h"

/***************************************************************************/
/* Autogenerated temporary variables as placeholders for pointer arguments */ 
/* and return value of function under test                                 */
/***************************************************************************/
INT	a = 5;
INT	b = 5;
INT	c = 5;




/***************************************************/
/* Autogenerated test matrix from tab: TEST_MATRIX */
/***************************************************/
ST_TEST_INPUTS st_arr_test_inputs[MAX_NUM_TEST_CASES] =
{    
    
	{
		&FUNC_UNDER_TEST,
		"",
		1,
		"",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"Comedy",
		8,
		"Comedy",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"MyCategory12345",
		16,
		"MyCategory12345",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"InvalidCategory12345",
		21,
		"InvalidCategory12345",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		NULL,
		0,
		NULL,
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"",
		1,
		"random",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"Comedy",
		8,
		"random",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"MyCategory12345",
		16,
		"random",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		"InvalidCategory12345",
		21,
		"random",
		"Dummy"
		
	},

	{
		&FUNC_UNDER_TEST,
		NULL,
		0,
		"random",
		"Dummy"
		
	}

/* e.g.    
    {
        &FUNC_UNDER_TEST,
        {
                0,
                0,
                0,
                0,
                SXI_MONITOR_SIGNAL_STATUS,
                SXI_SIG_STRENGTH_GOOD
        }
    }
*/
};


#endif

