
/****************************************************************************************/
/* File:           UTestImplementation.c                                                */
/* Description:    This file needs to be edited by user to call the function under test */
/*                 with proper arguments and to collect the result.*/ 
/*                 This file will be autogenerated in future to take care of TODO tags  */ 
/****************************************************************************************/
#include "UTestInterfaces.h"
#include "AutogeneratedTestData.h"
#include "LogInterfaces.h"


/**************************/
/* Local static functions */
/**************************/
static void set_global_vars(BYTE index);

#if __RET_TYP_NOT_VOID__
static void process_result(RETURN_TYPE expected, RETURN_TYPE actual, BYTE testID);
#endif



/**************************************************************************\
* Name:        fc_test_exec                                               *
* Input:                                                                  *
* Output:      None                                                       *
* Description: Unit test executer function. Can be autogenerated in future*
\**************************************************************************/
void fc_test_exec()
{
    BYTE index;

    /* TODO - Declare local variables for function parameters */
    /* e.g. PARAM1_TYPE arg1; */
    PARAM_0_TYPE	arg0;
	PARAM_1_TYPE	arg1;
	


    /* TODO - (Optional) declare local variables for return type */
#if __RET_TYP_NOT_VOID__
        RETURN_TYPE expected_res;
        RETURN_TYPE actual_res;
#endif


    for(index = 0; index < MAX_NUM_TEST_CASES; index++)
    {

        /* Set global variables */
        set_global_vars(index);

        /* TODO- populate the function arguments */
        /* e.g. arg1 = st_arr_test_inputs[index].arg1; */
        arg0 = st_arr_test_inputs[0].arg0;
		arg1 = st_arr_test_inputs[1].arg1;
		



        
#if __RET_TYP_NOT_VOID__
        expected_res = st_arr_test_inputs[index].ret_val;

        if(NULL != st_arr_test_inputs[index].fptr)
        {
            /* TODO - Edit following line to pass all arguments to the function */
            actual_res = st_arr_test_inputs[index].fptr(arg0, arg1);

            process_result(expected_res, actual_res, index);
        }
        else
        {
            /*printf("Null function pointer for testId: %d\n",index);*/
        }
#else

        if(NULL != st_arr_test_inputs[index].fptr)
        {

            /* TODO - Edit following line to pass all arguments to the function */
            st_arr_test_inputs[index].fptr(arg0, arg1);
        }
        else
        {
            /*printf("Null function pointer for testId: %d\n",index);*/
        }
#endif
        /* potentially pass this value to a logger for pass or fail */
    }
}

/****************************************************************************\
* Name:        set_global_vars                                              *
* Input:       index - index of current test case                           *
* Output:      None                                                         *
* Description: Write logic inside this function to set any global variables *
*              required to execute tests                                    *
\****************************************************************************/
static void set_global_vars(BYTE index)
{
    /* TODO - Your code here to initialize any global variables necessary for test */
    /* for example:  */
    /* bf_xxx_yyy_zzz_1 = st_arr_test_inputs[index].global_var_1 */
    /* memcpy(&Cat_Lab[0], st_arr_test_inputs[index].global_typ1, st_arr_test_inputs[index].arg2);*/
    z = st_arr_test_inputs[index].global_typ0;
	w = st_arr_test_inputs[index].global_typ1;
	


}


/****************************************************************************\
* Name:        process_result                                               *
* Input:       expected - Expected result                                   *
*              actual   - Actual result                                     *
*              testID   - Test number identifier                            *
* Output:      None                                                         *
* Description: Write logic inside this function to  log PASS or FAIL etc.   *
*              Or call another function to let's say, log a MOST message    *
\****************************************************************************/

#if __RET_TYP_NOT_VOID__
static void process_result(RETURN_TYPE expected, RETURN_TYPE actual, BYTE testID)
{
    /* TODO - (optional) Log pass or fail */
    /* example: */
    /* my_log(expected, actual, testID);*/
}
#endif

